# Generated by Django 4.1.7 on 2023-07-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_rename_razorpay_id_payment_razorpay_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_option",
            field=models.CharField(
                choices=[("cod", "cod"), ("razorpay", "razorpay")], max_length=20
            ),
        ),
    ]
