# Generated by Django 4.1.7 on 2023-07-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_order_total_amount_alter_order_payment_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_option",
            field=models.CharField(
                choices=[("cod", "cod"), ("razorpay", "razorpay")],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
