# Generated by Django 4.1.7 on 2023-07-26 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0007_payment_payment_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="order",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_address",
                to="order.order",
            ),
            preserve_default=False,
        ),
    ]
