# Generated by Django 4.1.7 on 2023-07-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0011_alter_payment_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="order",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipping_address",
                to="order.order",
            ),
        ),
    ]
